//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forgotten_Land_Launcher.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forgotten_Land_Launcher.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string article_text_on_date {
            get {
                return ResourceManager.GetString("article_text_on_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string article_text_posted_by {
            get {
                return ResourceManager.GetString("article_text_posted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete {0} addon?.
        /// </summary>
        public static string dialog_addon_remove_info {
            get {
                return ResourceManager.GetString("dialog_addon_remove_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Addon.
        /// </summary>
        public static string dialog_addon_remove_title {
            get {
                return ResourceManager.GetString("dialog_addon_remove_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a picture url.
        /// </summary>
        public static string dialog_avatar_change_text_picture_url {
            get {
                return ResourceManager.GetString("dialog_avatar_change_text_picture_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Settings.
        /// </summary>
        public static string dialog_avatar_change_title {
            get {
                return ResourceManager.GetString("dialog_avatar_change_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP.
        /// </summary>
        public static string dialog_buy_service_confirmation_text_dp {
            get {
                return ResourceManager.GetString("dialog_buy_service_confirmation_text_dp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP.
        /// </summary>
        public static string dialog_buy_service_confirmation_text_vp {
            get {
                return ResourceManager.GetString("dialog_buy_service_confirmation_text_vp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your purchase request...
        /// </summary>
        public static string dialog_buy_service_confirmation_text_wait {
            get {
                return ResourceManager.GetString("dialog_buy_service_confirmation_text_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string dialog_buy_service_confirmation_total_cost {
            get {
                return ResourceManager.GetString("dialog_buy_service_confirmation_total_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a duration.
        /// </summary>
        public static string dialog_characters_market_add_require_duration {
            get {
                return ResourceManager.GetString("dialog_characters_market_add_require_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current commission:.
        /// </summary>
        public static string dialog_characters_market_add_sale_commission {
            get {
                return ResourceManager.GetString("dialog_characters_market_add_sale_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a sale fee that will be deducted from you when the character is sold..
        /// </summary>
        public static string dialog_characters_market_add_sale_info {
            get {
                return ResourceManager.GetString("dialog_characters_market_add_sale_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Sale.
        /// </summary>
        public static string dialog_characters_market_add_sale_title {
            get {
                return ResourceManager.GetString("dialog_characters_market_add_sale_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be maximum.
        /// </summary>
        public static string dialog_characters_market_text_max_price {
            get {
                return ResourceManager.GetString("dialog_characters_market_text_max_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be minimum.
        /// </summary>
        public static string dialog_characters_market_text_min_price {
            get {
                return ResourceManager.GetString("dialog_characters_market_text_min_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you will receive.
        /// </summary>
        public static string dialog_characters_market_text_you_receive {
            get {
                return ResourceManager.GetString("dialog_characters_market_text_you_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired on.
        /// </summary>
        public static string dialog_inventory_item_acquired_on {
            get {
                return ResourceManager.GetString("dialog_inventory_item_acquired_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Claim.
        /// </summary>
        public static string dialog_inventory_item_claim_title {
            get {
                return ResourceManager.GetString("dialog_inventory_item_claim_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your characters...
        /// </summary>
        public static string dialog_inventory_item_text_loading_characters {
            get {
                return ResourceManager.GetString("dialog_inventory_item_text_loading_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no characters.
        /// </summary>
        public static string dialog_inventory_item_text_no_characters {
            get {
                return ResourceManager.GetString("dialog_inventory_item_text_no_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a character.
        /// </summary>
        public static string dialog_inventory_item_text_require_character {
            get {
                return ResourceManager.GetString("dialog_inventory_item_text_require_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter input.
        /// </summary>
        public static string dialog_inventory_item_text_require_input {
            get {
                return ResourceManager.GetString("dialog_inventory_item_text_require_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your claim request...
        /// </summary>
        public static string dialog_inventory_item_text_wait {
            get {
                return ResourceManager.GetString("dialog_inventory_item_text_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your claim request...
        /// </summary>
        public static string dialog_login_reward_text_wait {
            get {
                return ResourceManager.GetString("dialog_login_reward_text_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Reward.
        /// </summary>
        public static string dialog_login_reward_title {
            get {
                return ResourceManager.GetString("dialog_login_reward_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a redeem code.
        /// </summary>
        public static string dialog_redeem_gift_require_code {
            get {
                return ResourceManager.GetString("dialog_redeem_gift_require_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter a gift code.
        /// </summary>
        public static string dialog_redeem_gift_textbox_enter_code {
            get {
                return ResourceManager.GetString("dialog_redeem_gift_textbox_enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Gift Code.
        /// </summary>
        public static string dialog_redeem_gift_title {
            get {
                return ResourceManager.GetString("dialog_redeem_gift_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your request...
        /// </summary>
        public static string dialog_rquest_confirmation_text_wait {
            get {
                return ResourceManager.GetString("dialog_rquest_confirmation_text_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP.
        /// </summary>
        public static string dialog_shop_article_text_dp {
            get {
                return ResourceManager.GetString("dialog_shop_article_text_dp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string dialog_shop_article_text_total_cost {
            get {
                return ResourceManager.GetString("dialog_shop_article_text_total_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP.
        /// </summary>
        public static string dialog_shop_article_text_vp {
            get {
                return ResourceManager.GetString("dialog_shop_article_text_vp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading server...
        /// </summary>
        public static string discord_widget_text_loading {
            get {
                return ResourceManager.GetString("discord_widget_text_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBERS ONLINE.
        /// </summary>
        public static string discord_widget_text_members_online {
            get {
                return ResourceManager.GetString("discord_widget_text_members_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string exit_dialog_text {
            get {
                return ResourceManager.GetString("exit_dialog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Launcher.
        /// </summary>
        public static string exit_dialog_title {
            get {
                return ResourceManager.GetString("exit_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP UPDATE.
        /// </summary>
        public static string game_button_cancel_update {
            get {
                return ResourceManager.GetString("game_button_cancel_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string game_button_play {
            get {
                return ResourceManager.GetString("game_button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string game_button_update {
            get {
                return ResourceManager.GetString("game_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Clear Cache:.
        /// </summary>
        public static string game_popup_more_auto_clear_cache {
            get {
                return ResourceManager.GetString("game_popup_more_auto_clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login:.
        /// </summary>
        public static string game_popup_more_auto_login {
            get {
                return ResourceManager.GetString("game_popup_more_auto_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO LOGIN.
        /// </summary>
        public static string game_popup_more_auto_login_title {
            get {
                return ResourceManager.GetString("game_popup_more_auto_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string game_popup_more_check_for_updates {
            get {
                return ResourceManager.GetString("game_popup_more_check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR CACHE.
        /// </summary>
        public static string game_popup_more_clear_cache_title {
            get {
                return ResourceManager.GetString("game_popup_more_clear_cache_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD CLIENT.
        /// </summary>
        public static string game_popup_more_hd_client_title {
            get {
                return ResourceManager.GetString("game_popup_more_hd_client_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Models:.
        /// </summary>
        public static string game_popup_more_hd_models {
            get {
                return ResourceManager.GetString("game_popup_more_hd_models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game Folder.
        /// </summary>
        public static string game_popup_more_locate_game {
            get {
                return ResourceManager.GetString("game_popup_more_locate_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OPTIONS.
        /// </summary>
        public static string game_popup_more_options_title {
            get {
                return ResourceManager.GetString("game_popup_more_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string game_popup_more_select_language {
            get {
                return ResourceManager.GetString("game_popup_more_select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LANGUAGE.
        /// </summary>
        public static string game_popup_more_select_language_title {
            get {
                return ResourceManager.GetString("game_popup_more_select_language_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER STATUS.
        /// </summary>
        public static string game_popup_more_server_status_title {
            get {
                return ResourceManager.GetString("game_popup_more_server_status_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string game_popup_more_toggle_disable {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string game_popup_more_toggle_enable {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Game.
        /// </summary>
        public static string game_popup_more_toggle_full_game {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_full_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string game_popup_more_toggle_off {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string game_popup_more_toggle_on {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Updates.
        /// </summary>
        public static string game_popup_more_toggle_only_updates {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_only_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string game_popup_more_toggle_status_disabled {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_status_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string game_popup_more_toggle_status_enabled {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_status_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string game_popup_more_toggle_status_off {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_status_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string game_popup_more_toggle_status_on {
            get {
                return ResourceManager.GetString("game_popup_more_toggle_status_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify:.
        /// </summary>
        public static string game_popup_more_update_options {
            get {
                return ResourceManager.GetString("game_popup_more_update_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME VERIFY OPTIONS.
        /// </summary>
        public static string game_popup_more_update_options_title {
            get {
                return ResourceManager.GetString("game_popup_more_update_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path not set, please browse your game folder!.
        /// </summary>
        public static string game_popup_path_request_message {
            get {
                return ResourceManager.GetString("game_popup_path_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        public static string general_button_accept {
            get {
                return ResourceManager.GetString("general_button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE GAME.
        /// </summary>
        public static string general_button_browse_game {
            get {
                return ResourceManager.GetString("general_button_browse_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string general_button_cancel {
            get {
                return ResourceManager.GetString("general_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK.
        /// </summary>
        public static string general_button_check {
            get {
                return ResourceManager.GetString("general_button_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM.
        /// </summary>
        public static string general_button_claim {
            get {
                return ResourceManager.GetString("general_button_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string general_button_exit {
            get {
                return ResourceManager.GetString("general_button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string general_button_ok {
            get {
                return ResourceManager.GetString("general_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASE.
        /// </summary>
        public static string general_button_purchase {
            get {
                return ResourceManager.GetString("general_button_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ MORE.
        /// </summary>
        public static string general_button_readmore {
            get {
                return ResourceManager.GetString("general_button_readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string general_button_remove {
            get {
                return ResourceManager.GetString("general_button_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE OFFER.
        /// </summary>
        public static string general_button_set_bid {
            get {
                return ResourceManager.GetString("general_button_set_bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE.
        /// </summary>
        public static string general_button_use {
            get {
                return ResourceManager.GetString("general_button_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string general_dialog_text_processing {
            get {
                return ResourceManager.GetString("general_dialog_text_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string general_text_addon_author {
            get {
                return ResourceManager.GetString("general_text_addon_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string general_text_addon_size {
            get {
                return ResourceManager.GetString("general_text_addon_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string general_text_addon_version {
            get {
                return ResourceManager.GetString("general_text_addon_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic:.
        /// </summary>
        public static string general_text_discord_topic {
            get {
                return ResourceManager.GetString("general_text_discord_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active until.
        /// </summary>
        public static string general_text_event_active_until {
            get {
                return ResourceManager.GetString("general_text_event_active_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string general_text_level {
            get {
                return ResourceManager.GetString("general_text_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string general_text_ticket_closed {
            get {
                return ResourceManager.GetString("general_text_ticket_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string general_text_ticket_completed {
            get {
                return ResourceManager.GetString("general_text_ticket_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string general_text_ticket_pending {
            get {
                return ResourceManager.GetString("general_text_ticket_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        public static string general_text_ticket_viewed {
            get {
                return ResourceManager.GetString("general_text_ticket_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGELOGS.
        /// </summary>
        public static string home_navbar_button_changelog {
            get {
                return ResourceManager.GetString("home_navbar_button_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCORD.
        /// </summary>
        public static string home_navbar_button_discord {
            get {
                return ResourceManager.GetString("home_navbar_button_discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        public static string home_navbar_button_events {
            get {
                return ResourceManager.GetString("home_navbar_button_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string home_navbar_button_home {
            get {
                return ResourceManager.GetString("home_navbar_button_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string home_navbar_button_news {
            get {
                return ResourceManager.GetString("home_navbar_button_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donation points.
        /// </summary>
        public static string home_profile_donate_points {
            get {
                return ResourceManager.GetString("home_profile_donate_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote points.
        /// </summary>
        public static string home_profile_vote_points {
            get {
                return ResourceManager.GetString("home_profile_vote_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string language_bulgarian {
            get {
                return ResourceManager.GetString("language_bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string language_german {
            get {
                return ResourceManager.GetString("language_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string language_korean {
            get {
                return ResourceManager.GetString("language_korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string language_romanian {
            get {
                return ResourceManager.GetString("language_romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string language_russian {
            get {
                return ResourceManager.GetString("language_russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string language_spanish {
            get {
                return ResourceManager.GetString("language_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string left_menu_button_addons {
            get {
                return ResourceManager.GetString("left_menu_button_addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters Market.
        /// </summary>
        public static string left_menu_button_characters_market {
            get {
                return ResourceManager.GetString("left_menu_button_characters_market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string left_menu_button_faq {
            get {
                return ResourceManager.GetString("left_menu_button_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string left_menu_button_forum {
            get {
                return ResourceManager.GetString("left_menu_button_forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string left_menu_button_home {
            get {
                return ResourceManager.GetString("left_menu_button_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladderboards.
        /// </summary>
        public static string left_menu_button_ladderboard {
            get {
                return ResourceManager.GetString("left_menu_button_ladderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Players.
        /// </summary>
        public static string left_menu_button_online_players {
            get {
                return ResourceManager.GetString("left_menu_button_online_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string left_menu_button_shop {
            get {
                return ResourceManager.GetString("left_menu_button_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn Vote Points.
        /// </summary>
        public static string left_menu_button_vote {
            get {
                return ResourceManager.GetString("left_menu_button_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAIM NOW.
        /// </summary>
        public static string login_day_button_claim {
            get {
                return ResourceManager.GetString("login_day_button_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE.
        /// </summary>
        public static string login_window_button_change_password {
            get {
                return ResourceManager.GetString("login_window_button_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done reading.
        /// </summary>
        public static string login_window_button_done_reading {
            get {
                return ResourceManager.GetString("login_window_button_done_reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🡠 Back to Sign In.
        /// </summary>
        public static string login_window_button_other_back_to_sign_in {
            get {
                return ResourceManager.GetString("login_window_button_other_back_to_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a code 🡢.
        /// </summary>
        public static string login_window_button_other_have_reset_code {
            get {
                return ResourceManager.GetString("login_window_button_other_have_reset_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string login_window_button_other_recover {
            get {
                return ResourceManager.GetString("login_window_button_other_recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string login_window_button_other_register {
            get {
                return ResourceManager.GetString("login_window_button_other_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string login_window_button_other_sign_in {
            get {
                return ResourceManager.GetString("login_window_button_other_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Homepage 🡭.
        /// </summary>
        public static string login_window_button_other_visit_homepage {
            get {
                return ResourceManager.GetString("login_window_button_other_visit_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string login_window_button_register {
            get {
                return ResourceManager.GetString("login_window_button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND RECOVERY.
        /// </summary>
        public static string login_window_button_send_recovery {
            get {
                return ResourceManager.GetString("login_window_button_send_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string login_window_button_sign_in {
            get {
                return ResourceManager.GetString("login_window_button_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice.
        /// </summary>
        public static string login_window_checkbox_remember {
            get {
                return ResourceManager.GetString("login_window_checkbox_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the terms of service.
        /// </summary>
        public static string login_window_checkbox_terms_of_service {
            get {
                return ResourceManager.GetString("login_window_checkbox_terms_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string login_window_checkbox_terms_of_service_button {
            get {
                return ResourceManager.GetString("login_window_checkbox_terms_of_service_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while loading your account information and other data....
        /// </summary>
        public static string login_window_dialog_logging_in_text {
            get {
                return ResourceManager.GetString("login_window_dialog_logging_in_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        public static string login_window_dialog_logging_in_title {
            get {
                return ResourceManager.GetString("login_window_dialog_logging_in_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or you can do something else.
        /// </summary>
        public static string login_window_form_divider_placeholder_1 {
            get {
                return ResourceManager.GetString("login_window_form_divider_placeholder_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or you can go back.
        /// </summary>
        public static string login_window_form_divider_placeholder_2 {
            get {
                return ResourceManager.GetString("login_window_form_divider_placeholder_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..recovery code.
        /// </summary>
        public static string login_window_form_textbox_recovery_code {
            get {
                return ResourceManager.GetString("login_window_form_textbox_recovery_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string login_window_form_textbox_register_email {
            get {
                return ResourceManager.GetString("login_window_form_textbox_register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string login_window_form_textbox_register_username {
            get {
                return ResourceManager.GetString("login_window_form_textbox_register_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string login_window_form_textbox_username {
            get {
                return ResourceManager.GetString("login_window_form_textbox_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string login_window_powered_by {
            get {
                return ResourceManager.GetString("login_window_powered_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS OF SERVICE.
        /// </summary>
        public static string login_window_tos_title {
            get {
                return ResourceManager.GetString("login_window_tos_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is active.
        /// </summary>
        public static string page_account_info_account_active {
            get {
                return ResourceManager.GetString("page_account_info_account_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account banned until.
        /// </summary>
        public static string page_account_info_account_banned_until {
            get {
                return ResourceManager.GetString("page_account_info_account_banned_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT INVENTORY.
        /// </summary>
        public static string page_account_info_account_inventory {
            get {
                return ResourceManager.GetString("page_account_info_account_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEPORT.
        /// </summary>
        public static string page_account_info_button_teleport {
            get {
                return ResourceManager.GetString("page_account_info_button_teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNSTUCK.
        /// </summary>
        public static string page_account_info_button_unstuck {
            get {
                return ResourceManager.GetString("page_account_info_button_unstuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string page_account_info_button_update {
            get {
                return ResourceManager.GetString("page_account_info_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string page_account_info_destination {
            get {
                return ResourceManager.GetString("page_account_info_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change your public nickname to 🡢.
        /// </summary>
        public static string page_account_info_dialog_profile_info {
            get {
                return ResourceManager.GetString("page_account_info_dialog_profile_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public nickname.
        /// </summary>
        public static string page_account_info_dialog_profile_title {
            get {
                return ResourceManager.GetString("page_account_info_dialog_profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to teleport 🡢 {0} to {1}.
        /// </summary>
        public static string page_account_info_dialog_teleport_info {
            get {
                return ResourceManager.GetString("page_account_info_dialog_teleport_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Teleport.
        /// </summary>
        public static string page_account_info_dialog_teleport_title {
            get {
                return ResourceManager.GetString("page_account_info_dialog_teleport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to unstuck 🡢.
        /// </summary>
        public static string page_account_info_dialog_unstuck_info {
            get {
                return ResourceManager.GetString("page_account_info_dialog_unstuck_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Unstuck.
        /// </summary>
        public static string page_account_info_dialog_unstuck_title {
            get {
                return ResourceManager.GetString("page_account_info_dialog_unstuck_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last IP.
        /// </summary>
        public static string page_account_info_last_ip {
            get {
                return ResourceManager.GetString("page_account_info_last_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login on.
        /// </summary>
        public static string page_account_info_last_login_on {
            get {
                return ResourceManager.GetString("page_account_info_last_login_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY CHARACTERS.
        /// </summary>
        public static string page_account_info_my_characters {
            get {
                return ResourceManager.GetString("page_account_info_my_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets List.
        /// </summary>
        public static string page_account_info_my_tickets_list {
            get {
                return ResourceManager.GetString("page_account_info_my_tickets_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public profile id.
        /// </summary>
        public static string page_account_info_public_profile_id {
            get {
                return ResourceManager.GetString("page_account_info_public_profile_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport a character.
        /// </summary>
        public static string page_account_info_teleport_a_character {
            get {
                return ResourceManager.GetString("page_account_info_teleport_a_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading characters, please wait...
        /// </summary>
        public static string page_account_info_text_loading_characters {
            get {
                return ResourceManager.GetString("page_account_info_text_loading_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading destinations, please wait...
        /// </summary>
        public static string page_account_info_text_loading_destinations {
            get {
                return ResourceManager.GetString("page_account_info_text_loading_destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no characters...
        /// </summary>
        public static string page_account_info_text_no_characters {
            get {
                return ResourceManager.GetString("page_account_info_text_no_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destinations available.
        /// </summary>
        public static string page_account_info_text_no_destinations {
            get {
                return ResourceManager.GetString("page_account_info_text_no_destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no tickets.
        /// </summary>
        public static string page_account_info_text_no_tickets {
            get {
                return ResourceManager.GetString("page_account_info_text_no_tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a character.
        /// </summary>
        public static string page_account_info_text_require_character {
            get {
                return ResourceManager.GetString("page_account_info_text_require_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination.
        /// </summary>
        public static string page_account_info_text_require_destination {
            get {
                return ResourceManager.GetString("page_account_info_text_require_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstuck a character.
        /// </summary>
        public static string page_account_info_unstuck_a_character {
            get {
                return ResourceManager.GetString("page_account_info_unstuck_a_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT INVENTORY.
        /// </summary>
        public static string page_account_inventory_title {
            get {
                return ResourceManager.GetString("page_account_inventory_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDONS.
        /// </summary>
        public static string page_addons_title {
            get {
                return ResourceManager.GetString("page_addons_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGELOGS.
        /// </summary>
        public static string page_changelogs_title {
            get {
                return ResourceManager.GetString("page_changelogs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string page_characters_market_button_cancel_sale {
            get {
                return ResourceManager.GetString("page_characters_market_button_cancel_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More...
        /// </summary>
        public static string page_characters_market_button_more_info {
            get {
                return ResourceManager.GetString("page_characters_market_button_more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SALES.
        /// </summary>
        public static string page_characters_market_button_my_sales {
            get {
                return ResourceManager.GetString("page_characters_market_button_my_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string page_characters_market_button_search {
            get {
                return ResourceManager.GetString("page_characters_market_button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELL.
        /// </summary>
        public static string page_characters_market_button_sell {
            get {
                return ResourceManager.GetString("page_characters_market_button_sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in.
        /// </summary>
        public static string page_characters_market_card_text_expires_in {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_expires_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed price.
        /// </summary>
        public static string page_characters_market_card_text_fixed_price {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_fixed_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold:.
        /// </summary>
        public static string page_characters_market_card_text_gold {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest bid.
        /// </summary>
        public static string page_characters_market_card_text_highest_bid {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_highest_bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string page_characters_market_card_text_level {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions:.
        /// </summary>
        public static string page_characters_market_card_text_professions {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Score:.
        /// </summary>
        public static string page_characters_market_card_text_pvp_score {
            get {
                return ResourceManager.GetString("page_characters_market_card_text_pvp_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO TO ARMORY.
        /// </summary>
        public static string page_characters_market_dialog_button_armory {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_button_armory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won auction.
        /// </summary>
        public static string page_characters_market_dialog_subtitle_won_auction {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_subtitle_won_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer.
        /// </summary>
        public static string page_characters_market_dialog_text_buy_bid_amount {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_buy_bid_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bidding.
        /// </summary>
        public static string page_characters_market_dialog_text_current_bid {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_current_bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP.
        /// </summary>
        public static string page_characters_market_dialog_text_dp {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_dp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of gold held:.
        /// </summary>
        public static string page_characters_market_dialog_text_gold_held {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_gold_held", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professions learned.
        /// </summary>
        public static string page_characters_market_dialog_text_professions {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached PvP score of:.
        /// </summary>
        public static string page_characters_market_dialog_text_pvp_score {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_pvp_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        public static string page_characters_market_dialog_text_sale_price {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_text_sale_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string page_characters_market_dialog_title_congratulations {
            get {
                return ResourceManager.GetString("page_characters_market_dialog_title_congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired price.
        /// </summary>
        public static string page_characters_market_requested_price {
            get {
                return ResourceManager.GetString("page_characters_market_requested_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial bidding price.
        /// </summary>
        public static string page_characters_market_starting_bid_price {
            get {
                return ResourceManager.GetString("page_characters_market_starting_bid_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        public static string page_characters_market_textbox_player_search {
            get {
                return ResourceManager.GetString("page_characters_market_textbox_player_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARACTERS MARKET.
        /// </summary>
        public static string page_characters_market_title {
            get {
                return ResourceManager.GetString("page_characters_market_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK TO MESSAGES.
        /// </summary>
        public static string page_create_message_button_back {
            get {
                return ResourceManager.GetString("page_create_message_button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND MESSAGE.
        /// </summary>
        public static string page_create_message_button_send {
            get {
                return ResourceManager.GetString("page_create_message_button_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Delivery.
        /// </summary>
        public static string page_create_message_dialog_delivery_title {
            get {
                return ResourceManager.GetString("page_create_message_dialog_delivery_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send the message you composed?.
        /// </summary>
        public static string page_create_message_dialog_info {
            get {
                return ResourceManager.GetString("page_create_message_dialog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send New Message.
        /// </summary>
        public static string page_create_message_dialog_title {
            get {
                return ResourceManager.GetString("page_create_message_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters:.
        /// </summary>
        public static string page_create_message_text_characters {
            get {
                return ResourceManager.GetString("page_create_message_text_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string page_create_message_textbox_message_subject {
            get {
                return ResourceManager.GetString("page_create_message_textbox_message_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver nickname.
        /// </summary>
        public static string page_create_message_textbox_nickname {
            get {
                return ResourceManager.GetString("page_create_message_textbox_nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE A NEW MESSAGE.
        /// </summary>
        public static string page_create_message_title {
            get {
                return ResourceManager.GetString("page_create_message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENTLY ASKED QUESTIONS.
        /// </summary>
        public static string page_faq_title {
            get {
                return ResourceManager.GetString("page_faq_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASS.
        /// </summary>
        public static string page_ladderboards_column_class {
            get {
                return ResourceManager.GetString("page_ladderboards_column_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string page_ladderboards_column_name {
            get {
                return ResourceManager.GetString("page_ladderboards_column_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RACE.
        /// </summary>
        public static string page_ladderboards_column_race {
            get {
                return ResourceManager.GetString("page_ladderboards_column_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REALM.
        /// </summary>
        public static string page_ladderboards_column_realm_name {
            get {
                return ResourceManager.GetString("page_ladderboards_column_realm_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY KILLS.
        /// </summary>
        public static string page_ladderboards_column_today_kills {
            get {
                return ResourceManager.GetString("page_ladderboards_column_today_kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL KILLS.
        /// </summary>
        public static string page_ladderboards_column_total_kills {
            get {
                return ResourceManager.GetString("page_ladderboards_column_total_kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YESTERDAY KILLS.
        /// </summary>
        public static string page_ladderboards_column_yesterday_kills {
            get {
                return ResourceManager.GetString("page_ladderboards_column_yesterday_kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADDERBOARDS.
        /// </summary>
        public static string page_ladderboards_title {
            get {
                return ResourceManager.GetString("page_ladderboards_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page is loading, please wait...
        /// </summary>
        public static string page_loading_message {
            get {
                return ResourceManager.GetString("page_loading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page is temporarily locked, please come back later...
        /// </summary>
        public static string page_locked_message {
            get {
                return ResourceManager.GetString("page_locked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN REWARDS.
        /// </summary>
        public static string page_login_rewards_title {
            get {
                return ResourceManager.GetString("page_login_rewards_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string page_message_view_button_back {
            get {
                return ResourceManager.GetString("page_message_view_button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPLY.
        /// </summary>
        public static string page_message_view_button_reply {
            get {
                return ResourceManager.GetString("page_message_view_button_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Delivery.
        /// </summary>
        public static string page_message_view_dialog_delivery_title {
            get {
                return ResourceManager.GetString("page_message_view_dialog_delivery_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send the reply you composed?.
        /// </summary>
        public static string page_message_view_dialog_info {
            get {
                return ResourceManager.GetString("page_message_view_dialog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send New Reply.
        /// </summary>
        public static string page_message_view_dialog_title {
            get {
                return ResourceManager.GetString("page_message_view_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reply...
        /// </summary>
        public static string page_message_view_textbox_reply {
            get {
                return ResourceManager.GetString("page_message_view_textbox_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string page_messages_button_create_new {
            get {
                return ResourceManager.GetString("page_messages_button_create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE MESSAGES.
        /// </summary>
        public static string page_messages_title {
            get {
                return ResourceManager.GetString("page_messages_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE PLAYERS.
        /// </summary>
        public static string page_online_players_title {
            get {
                return ResourceManager.GetString("page_online_players_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string page_shop_all_categories {
            get {
                return ResourceManager.GetString("page_shop_all_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string page_shop_dialog_title_fail {
            get {
                return ResourceManager.GetString("page_shop_dialog_title_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string page_shop_dialog_title_success {
            get {
                return ResourceManager.GetString("page_shop_dialog_title_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOP.
        /// </summary>
        public static string page_shop_title {
            get {
                return ResourceManager.GetString("page_shop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOTE TO EARN POINTS.
        /// </summary>
        public static string page_vote_title {
            get {
                return ResourceManager.GetString("page_vote_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string slider_button_learn_more {
            get {
                return ResourceManager.GetString("slider_button_learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOTE.
        /// </summary>
        public static string vote_button {
            get {
                return ResourceManager.GetString("vote_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for this site ({0})?.
        /// </summary>
        public static string vote_dialog_text {
            get {
                return ResourceManager.GetString("vote_dialog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Site.
        /// </summary>
        public static string vote_dialog_title {
            get {
                return ResourceManager.GetString("vote_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown left:.
        /// </summary>
        public static string vote_text_cooldown_left {
            get {
                return ResourceManager.GetString("vote_text_cooldown_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points reward:.
        /// </summary>
        public static string vote_text_points_reward {
            get {
                return ResourceManager.GetString("vote_text_points_reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string vote_text_ready {
            get {
                return ResourceManager.GetString("vote_text_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue manually...
        /// </summary>
        public static string window_game_login_overlay_button_continue {
            get {
                return ResourceManager.GetString("window_game_login_overlay_button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE GAME IS LOADED, YOU CAN PLAY.
        /// </summary>
        public static string window_game_login_text_game_loaded {
            get {
                return ResourceManager.GetString("window_game_login_text_game_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE WAIT FOR THE GAME TO LOAD FIRST, THEN YOU CAN SIGN IN!.
        /// </summary>
        public static string window_game_login_text_wait {
            get {
                return ResourceManager.GetString("window_game_login_text_wait", resourceCulture);
            }
        }
    }
}
