<?php
/*

█▄█ ███ ███ ███ ███ █┼┼█ ┼┼ ███ ███ ███
███ ┼█┼ █▄▄ ┼█┼ █┼█ ██▄█ ┼┼ █▄█ █▄█ ┼█┼
┼█┼ ▄█▄ ▄▄█ ▄█▄ █▄█ █┼██ ┼┼ █┼█ █┼┼ ▄█▄

Copyrights @ cybermist2 2024-present

API built by cybermist2@gmail.com

*/

namespace vISION;

class SQL_QUERIES
{
    public static function GET(string $name, int $emulator)
    {
        return self::$QUERIES_LIST[$name][$emulator];
    }

    protected static $QUERIES_LIST = [

        'AUTH_VERIFY_SHA_PASS_HASH' => [
            MANGOS_ONE                  => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            MANGOS_TWO                  => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            MANGOS_THREE                => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            MANGOS_FOUR                 => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            MANGOS_FIVE                 => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            SKYFIRE_MOP                 => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            LEGIONCORE_735_SHA          => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT 1 FROM account WHERE username = ? AND sha_pass_hash = ?',
        ],

        'AUTH_GET_SALT_VERIFIER_BY_USERNAME' => [
            TRINITYCORE_WOTLK           => 'SELECT salt, verifier FROM account WHERE username = ?',
            TRINITYCORE_CATA            => 'SELECT salt, verifier FROM account WHERE username = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT salt, verifier FROM account WHERE username = ?',
            MANGOS_ONE                  => 'SELECT s, v FROM account WHERE username = ?',
            MANGOS_TWO                  => 'SELECT s, v FROM account WHERE username = ?',
            MANGOS_THREE                => 'SELECT s, v FROM account WHERE username = ?',
            MANGOS_FOUR                 => 'SELECT s, v FROM account WHERE username = ?',
            MANGOS_FIVE                 => 'SELECT s, v FROM account WHERE username = ?',
            CMANGOS_CLASSIC             => 'SELECT s, v FROM account WHERE username = ?',
            CMANGOS_TBC                 => 'SELECT s, v FROM account WHERE username = ?',
            CMANGOS_WOTLK               => 'SELECT s, v FROM account WHERE username = ?',
            CMANGOS_CATA                => 'SELECT s, v FROM account WHERE username = ?',
            VMANGOS_CLASSIC             => 'SELECT s, v FROM account WHERE username = ?',
            AZEROTHCORE_WOTLK           => 'SELECT salt, verifier FROM account WHERE username = ?',
            SKYFIRE_MOP                 => 'SELECT s, v FROM account WHERE username = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT salt, verifier FROM account WHERE username = ?',
            ATLANTISS_CATA              => 'SELECT salt, verifier FROM account WHERE username = ?',
            LEGIONCORE_735_SHA          => 'SELECT s, v FROM account WHERE username = ?',
        ],

        'AUTH_INSERT_V_S_ACCOUNT' => [
            TRINITYCORE_WOTLK           => 'INSERT INTO account (username, salt, verifier, email, expansion) VALUES (?, ?, ?, ?, 2)',
            TRINITYCORE_DRAGONFLIGHTS   => 'INSERT INTO account (username, salt, verifier, email, expansion) VALUES (?, ?, ?, ?, 10)',
            MANGOS_ONE                  => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 1)',
            MANGOS_TWO                  => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 2)',
            MANGOS_THREE                => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 3)',
            MANGOS_FOUR                 => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 4)',
            MANGOS_FIVE                 => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 5)',
            CMANGOS_CLASSIC             => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 0)',
            CMANGOS_TBC                 => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 1)',
            CMANGOS_WOTLK               => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 2)',
            CMANGOS_CATA                => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 3)',
            VMANGOS_CLASSIC             => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 0)',
            AZEROTHCORE_WOTLK           => 'INSERT INTO account (username, salt, verifier, email, expansion) VALUES (?, ?, ?, ?, 2)',
            ASHMANE_SHADOWLANDS         => 'INSERT INTO account (username, salt, verifier, email, expansion) VALUES (?, ?, ?, ?, 9)',
            ATLANTISS_CATA              => 'INSERT INTO account (username, salt, verifier, email, expansion) VALUES (?, ?, ?, ?, 4)',
            LEGIONCORE_735_SHA          => 'INSERT INTO account (username, s, v, email, expansion) VALUES (?, ?, ?, ?, 7)',
        ],

        'AUTH_INSERT_SHA_PASS_HASH_ACCOUNT' => [
            TRINITYCORE_CATA            => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 4)',
            MANGOS_ONE                  => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 1)',
            MANGOS_TWO                  => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 2)',
            MANGOS_THREE                => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 3)',
            MANGOS_FOUR                 => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 4)',
            MANGOS_FIVE                 => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 5)',
            SKYFIRE_MOP                 => 'INSERT INTO account (username, sha_pass_hash, email, mutereason, joindate, last_login, expansion) VALUES (?, ?, ?, "unknown", NOW(), NOW(), 5)',
            LEGIONCORE_735_SHA          => 'INSERT INTO account (username, sha_pass_hash, email, mutereason, joindate, last_login, expansion) VALUES (?, ?, ?, "unknown", NOW(), NOW(), 7)',
            TRINITYCORE_WOTLK_2016      => 'INSERT INTO account (username, sha_pass_hash, email, expansion) VALUES (?, ?, ?, 2)',
        ],

        'AUTH_UPDATE_S_V_PASSWORD' => [
            TRINITYCORE_WOTLK           => 'UPDATE account SET salt = ?, verifier = ? WHERE username = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE account SET salt = ?, verifier = ? WHERE username = ?',
            MANGOS_ONE                  => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            MANGOS_TWO                  => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            MANGOS_THREE                => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            MANGOS_FOUR                 => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            MANGOS_FIVE                 => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            CMANGOS_CLASSIC             => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            CMANGOS_TBC                 => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            CMANGOS_WOTLK               => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            CMANGOS_CATA                => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            VMANGOS_CLASSIC             => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
            AZEROTHCORE_WOTLK           => 'UPDATE account SET salt = ?, verifier = ? WHERE username = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE account SET salt = ?, verifier = ? WHERE username = ?',
            ATLANTISS_CATA              => 'UPDATE account SET salt = ?, verifier = ? WHERE username = ?',
            LEGIONCORE_735_SHA          => 'UPDATE account SET s = ?, v = ? WHERE username = ?',
        ],

        'AUTH_UPDATE_SHA_PASS_HASH_PASSWORD' => [
            TRINITYCORE_CATA            => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            MANGOS_ONE                  => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            MANGOS_TWO                  => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            MANGOS_THREE                => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            MANGOS_FOUR                 => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            MANGOS_FIVE                 => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            SKYFIRE_MOP                 => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            LEGIONCORE_735_SHA          => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
            TRINITYCORE_WOTLK_2016      => 'UPDATE account SET sha_pass_hash = ? WHERE username = ?',
        ],

        'AUTH_INSERT_BATTLENET_PASSWORD' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE battlenet_accounts SET sha_pass_hash = ? WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE battlenet_accounts SET sha_pass_hash = ? WHERE email = ?',
            LEGIONCORE_735_SHA          => 'UPDATE battlenet_accounts SET sha_pass_hash = ? WHERE email = ?',
        ],

        'AUTH_GET_ACCOUNT_ID_BY_USERNAME' => [
            TRINITYCORE_WOTLK           => 'SELECT id FROM account WHERE username = ?',
            TRINITYCORE_CATA            => 'SELECT id FROM account WHERE username = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT id FROM account WHERE username = ?',
            MANGOS_ONE                  => 'SELECT id FROM account WHERE username = ?',
            MANGOS_TWO                  => 'SELECT id FROM account WHERE username = ?',
            MANGOS_THREE                => 'SELECT id FROM account WHERE username = ?',
            MANGOS_FOUR                 => 'SELECT id FROM account WHERE username = ?',
            MANGOS_FIVE                 => 'SELECT id FROM account WHERE username = ?',
            CMANGOS_CLASSIC             => 'SELECT id FROM account WHERE username = ?',
            CMANGOS_TBC                 => 'SELECT id FROM account WHERE username = ?',
            CMANGOS_WOTLK               => 'SELECT id FROM account WHERE username = ?',
            CMANGOS_CATA                => 'SELECT id FROM account WHERE username = ?',
            VMANGOS_CLASSIC             => 'SELECT id FROM account WHERE username = ?',
            AZEROTHCORE_WOTLK           => 'SELECT id FROM account WHERE username = ?',
            SKYFIRE_MOP                 => 'SELECT id FROM account WHERE username = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT id FROM account WHERE username = ?',
            ATLANTISS_CATA              => 'SELECT id FROM account WHERE username = ?',
            LEGIONCORE_735_SHA          => 'SELECT id FROM account WHERE username = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT id FROM account WHERE username = ?',
        ],

        'AUTH_GET_ACCOUNT_IS_ACTIVE_BY_USERNAME' => [
            TRINITYCORE_WOTLK           => 'SELECT isActive FROM account WHERE username = ?',
            TRINITYCORE_CATA            => 'SELECT isActive FROM account WHERE username = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT isActive FROM account WHERE username = ?',
            MANGOS_ONE                  => 'SELECT isActive FROM account WHERE username = ?',
            MANGOS_TWO                  => 'SELECT isActive FROM account WHERE username = ?',
            MANGOS_THREE                => 'SELECT isActive FROM account WHERE username = ?',
            MANGOS_FOUR                 => 'SELECT isActive FROM account WHERE username = ?',
            MANGOS_FIVE                 => 'SELECT isActive FROM account WHERE username = ?',
            CMANGOS_CLASSIC             => 'SELECT isActive FROM account WHERE username = ?',
            CMANGOS_TBC                 => 'SELECT isActive FROM account WHERE username = ?',
            CMANGOS_WOTLK               => 'SELECT isActive FROM account WHERE username = ?',
            CMANGOS_CATA                => 'SELECT isActive FROM account WHERE username = ?',
            VMANGOS_CLASSIC             => 'SELECT isActive FROM account WHERE username = ?',
            AZEROTHCORE_WOTLK           => 'SELECT isActive FROM account WHERE username = ?',
            SKYFIRE_MOP                 => 'SELECT isActive FROM account WHERE username = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT isActive FROM account WHERE username = ?',
            ATLANTISS_CATA              => 'SELECT isActive FROM account WHERE username = ?',
            LEGIONCORE_735_SHA          => 'SELECT isActive FROM account WHERE username = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT isActive FROM account WHERE username = ?',
        ],

        'AUTH_GET_EMAIL_BY_USERNAME' => [
            TRINITYCORE_WOTLK           => 'SELECT email FROM account WHERE username = ?',
            TRINITYCORE_CATA            => 'SELECT email FROM account WHERE username = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT email FROM account WHERE username = ?',
            MANGOS_ONE                  => 'SELECT email FROM account WHERE username = ?',
            MANGOS_TWO                  => 'SELECT email FROM account WHERE username = ?',
            MANGOS_THREE                => 'SELECT email FROM account WHERE username = ?',
            MANGOS_FOUR                 => 'SELECT email FROM account WHERE username = ?',
            MANGOS_FIVE                 => 'SELECT email FROM account WHERE username = ?',
            CMANGOS_CLASSIC             => 'SELECT email FROM account WHERE username = ?',
            CMANGOS_TBC                 => 'SELECT email FROM account WHERE username = ?',
            CMANGOS_WOTLK               => 'SELECT email FROM account WHERE username = ?',
            CMANGOS_CATA                => 'SELECT email FROM account WHERE username = ?',
            VMANGOS_CLASSIC             => 'SELECT email FROM account WHERE username = ?',
            AZEROTHCORE_WOTLK           => 'SELECT email FROM account WHERE username = ?',
            SKYFIRE_MOP                 => 'SELECT email FROM account WHERE username = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT email FROM account WHERE username = ?',
            ATLANTISS_CATA              => 'SELECT email FROM account WHERE username = ?',
            LEGIONCORE_735_SHA          => 'SELECT email FROM account WHERE username = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT email FROM account WHERE username = ?',
        ],

        'AUTH_GET_ACCOUNT_NAME_BY_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT username FROM account WHERE id = ?',
            TRINITYCORE_CATA            => 'SELECT username FROM account WHERE id = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT username FROM account WHERE id = ?',
            MANGOS_ONE                  => 'SELECT username FROM account WHERE id = ?',
            MANGOS_TWO                  => 'SELECT username FROM account WHERE id = ?',
            MANGOS_THREE                => 'SELECT username FROM account WHERE id = ?',
            MANGOS_FOUR                 => 'SELECT username FROM account WHERE id = ?',
            MANGOS_FIVE                 => 'SELECT username FROM account WHERE id = ?',
            CMANGOS_CLASSIC             => 'SELECT username FROM account WHERE id = ?',
            CMANGOS_TBC                 => 'SELECT username FROM account WHERE id = ?',
            CMANGOS_WOTLK               => 'SELECT username FROM account WHERE id = ?',
            CMANGOS_CATA                => 'SELECT username FROM account WHERE id = ?',
            VMANGOS_CLASSIC             => 'SELECT username FROM account WHERE id = ?',
            AZEROTHCORE_WOTLK           => 'SELECT username FROM account WHERE id = ?',
            SKYFIRE_MOP                 => 'SELECT username FROM account WHERE id = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT username FROM account WHERE id = ?',
            ATLANTISS_CATA              => 'SELECT username FROM account WHERE id = ?',
            LEGIONCORE_735_SHA          => 'SELECT username FROM account WHERE id = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT username FROM account WHERE id = ?',
        ],

        'AUTH_GET_ACCOUNT_NAME_BY_EMAIL' => [
            TRINITYCORE_WOTLK           => 'SELECT username FROM account WHERE email = ?',
            TRINITYCORE_CATA            => 'SELECT username FROM account WHERE email = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT username FROM account WHERE email = ?',
            MANGOS_ONE                  => 'SELECT username FROM account WHERE email = ?',
            MANGOS_TWO                  => 'SELECT username FROM account WHERE email = ?',
            MANGOS_THREE                => 'SELECT username FROM account WHERE email = ?',
            MANGOS_FOUR                 => 'SELECT username FROM account WHERE email = ?',
            MANGOS_FIVE                 => 'SELECT username FROM account WHERE email = ?',
            CMANGOS_CLASSIC             => 'SELECT username FROM account WHERE email = ?',
            CMANGOS_TBC                 => 'SELECT username FROM account WHERE email = ?',
            CMANGOS_WOTLK               => 'SELECT username FROM account WHERE email = ?',
            CMANGOS_CATA                => 'SELECT username FROM account WHERE email = ?',
            VMANGOS_CLASSIC             => 'SELECT username FROM account WHERE email = ?',
            AZEROTHCORE_WOTLK           => 'SELECT username FROM account WHERE email = ?',
            SKYFIRE_MOP                 => 'SELECT username FROM account WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT username FROM account WHERE email = ?',
            ATLANTISS_CATA              => 'SELECT username FROM account WHERE email = ?',
            LEGIONCORE_735_SHA          => 'SELECT username FROM account WHERE email = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT username FROM account WHERE email = ?',
        ],

        'AUTH_GET_ACCOUNT_LAST_LOGIN_BY_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            TRINITYCORE_CATA            => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            MANGOS_ONE                  => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            MANGOS_TWO                  => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            MANGOS_THREE                => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            MANGOS_FOUR                 => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            MANGOS_FIVE                 => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            CMANGOS_CLASSIC             => 'SELECT DATE_FORMAT(COALESCE(loginTime, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account_logons WHERE accountId = ?',
            CMANGOS_TBC                 => 'SELECT DATE_FORMAT(COALESCE(loginTime, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account_logons WHERE accountId = ?',
            CMANGOS_WOTLK               => 'SELECT DATE_FORMAT(COALESCE(loginTime, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account_logons WHERE accountId = ?',
            CMANGOS_CATA                => 'SELECT DATE_FORMAT(COALESCE(loginTime, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account_logons WHERE accountId = ?',
            VMANGOS_CLASSIC             => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            AZEROTHCORE_WOTLK           => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            SKYFIRE_MOP                 => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            ATLANTISS_CATA              => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            LEGIONCORE_735_SHA          => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT DATE_FORMAT(COALESCE(last_login, NOW()), "%e %M %Y, %H:%i") AS formatted_timestamp FROM account WHERE id = ?',
        ],

        'AUTH_GET_ACCOUNT_LAST_LOGIN_IP_BY_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT last_ip FROM account WHERE id = ?',
            TRINITYCORE_CATA            => 'SELECT last_ip FROM account WHERE id = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT last_ip FROM account WHERE id = ?',
            MANGOS_ONE                  => 'SELECT last_ip FROM account WHERE id = ?',
            MANGOS_TWO                  => 'SELECT last_ip FROM account WHERE id = ?',
            MANGOS_THREE                => 'SELECT last_ip FROM account WHERE id = ?',
            MANGOS_FOUR                 => 'SELECT last_ip FROM account WHERE id = ?',
            MANGOS_FIVE                 => 'SELECT last_ip FROM account WHERE id = ?',
            CMANGOS_CLASSIC             => 'SELECT COALESCE(ip, "127.0.0.1") FROM account_logons WHERE accountId = ?',
            CMANGOS_TBC                 => 'SELECT COALESCE(ip, "127.0.0.1") FROM account_logons WHERE accountId = ?',
            CMANGOS_WOTLK               => 'SELECT COALESCE(ip, "127.0.0.1") FROM account_logons WHERE accountId = ?',
            CMANGOS_CATA                => 'SELECT COALESCE(ip, "127.0.0.1") FROM account_logons WHERE accountId = ?',
            VMANGOS_CLASSIC             => 'SELECT last_ip FROM account WHERE id = ?',
            AZEROTHCORE_WOTLK           => 'SELECT last_ip FROM account WHERE id = ?',
            SKYFIRE_MOP                 => 'SELECT last_ip FROM account WHERE id = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT last_ip FROM account WHERE id = ?',
            ATLANTISS_CATA              => 'SELECT last_ip FROM account WHERE id = ?',
            LEGIONCORE_735_SHA          => 'SELECT last_ip FROM account WHERE id = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT last_ip FROM account WHERE id = ?',
        ],

        'AUTH_GET_ACCOUNT_RANK_BY_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT SecurityLevel FROM account_access WHERE AccountID = ?',
            TRINITYCORE_CATA            => 'SELECT SecurityLevel FROM account_access WHERE AccountID = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT SecurityLevel FROM account_access WHERE AccountID = ?',
            MANGOS_ONE                  => 'SELECT gmlevel FROM account WHERE id = ?',
            MANGOS_TWO                  => 'SELECT gmlevel FROM account WHERE id = ?',
            MANGOS_THREE                => 'SELECT gmlevel FROM account WHERE id = ?',
            MANGOS_FOUR                 => 'SELECT gmlevel FROM account WHERE id = ?',
            MANGOS_FIVE                 => 'SELECT gmlevel FROM account WHERE id = ?',
            CMANGOS_CLASSIC             => 'SELECT gmlevel FROM account WHERE id = ?',
            CMANGOS_TBC                 => 'SELECT gmlevel FROM account WHERE id = ?',
            CMANGOS_WOTLK               => 'SELECT gmlevel FROM account WHERE id = ?',
            CMANGOS_CATA                => 'SELECT gmlevel FROM account WHERE id = ?',
            VMANGOS_CLASSIC             => 'SELECT gmlevel FROM account WHERE id = ?',
            AZEROTHCORE_WOTLK           => 'SELECT gmlevel FROM account_access WHERE id = ?',
            SKYFIRE_MOP                 => 'SELECT gmlevel FROM account_access WHERE id = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT SecurityLevel FROM account WHERE AccountID = ?',
            ATLANTISS_CATA              => 'SELECT SecurityLevel FROM account_access WHERE AccountID = ?',
            LEGIONCORE_735_SHA          => 'SELECT gmlevel FROM account_access WHERE id = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT gmlevel FROM account_access WHERE id = ?',
        ],

        'AUTH_GET_USERNAME_BY_MD5HASH' => [
            TRINITYCORE_WOTLK           => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_CATA            => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_ONE                  => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_TWO                  => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_THREE                => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_FOUR                 => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_FIVE                 => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_CLASSIC             => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_TBC                 => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_WOTLK               => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_CATA                => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            VMANGOS_CLASSIC             => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            AZEROTHCORE_WOTLK           => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            SKYFIRE_MOP                 => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            ASHMANE_SHADOWLANDS         => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            ATLANTISS_CATA              => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            LEGIONCORE_735_SHA          => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_WOTLK_2016      => 'SELECT username FROM account WHERE ? = MD5(LOWER(username))',
        ],

        'AUTH_GET_EMAIL_BY_MD5HASH' => [
            TRINITYCORE_WOTLK           => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            TRINITYCORE_CATA            => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            MANGOS_ONE                  => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            MANGOS_TWO                  => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            MANGOS_THREE                => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            MANGOS_FOUR                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            MANGOS_FIVE                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            CMANGOS_CLASSIC             => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            CMANGOS_TBC                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            CMANGOS_WOTLK               => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            CMANGOS_CATA                => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            VMANGOS_CLASSIC             => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            AZEROTHCORE_WOTLK           => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            SKYFIRE_MOP                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            ASHMANE_SHADOWLANDS         => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            ATLANTISS_CATA              => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            LEGIONCORE_735_SHA          => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
            TRINITYCORE_WOTLK_2016      => 'SELECT email FROM account WHERE ? = MD5(LOWER(email))',
        ],

        'AUTH_GET_ACCOUNT_ID_BY_EMAIL' => [
            TRINITYCORE_WOTLK           => 'SELECT id FROM account WHERE email = ?',
            TRINITYCORE_CATA            => 'SELECT id FROM account WHERE email = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT id FROM account WHERE email = ?',
            MANGOS_ONE                  => 'SELECT id FROM account WHERE email = ?',
            MANGOS_TWO                  => 'SELECT id FROM account WHERE email = ?',
            MANGOS_THREE                => 'SELECT id FROM account WHERE email = ?',
            MANGOS_FOUR                 => 'SELECT id FROM account WHERE email = ?',
            MANGOS_FIVE                 => 'SELECT id FROM account WHERE email = ?',
            CMANGOS_CLASSIC             => 'SELECT id FROM account WHERE email = ?',
            CMANGOS_TBC                 => 'SELECT id FROM account WHERE email = ?',
            CMANGOS_WOTLK               => 'SELECT id FROM account WHERE email = ?',
            CMANGOS_CATA                => 'SELECT id FROM account WHERE email = ?',
            VMANGOS_CLASSIC             => 'SELECT id FROM account WHERE email = ?',
            AZEROTHCORE_WOTLK           => 'SELECT id FROM account WHERE email = ?',
            SKYFIRE_MOP                 => 'SELECT id FROM account WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT id FROM account WHERE email = ?',
            ATLANTISS_CATA              => 'SELECT id FROM account WHERE email = ?',
            LEGIONCORE_735_SHA          => 'SELECT id FROM account WHERE email = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT id FROM account WHERE email = ?',
        ],

        'AUTH_GET_BATTLEPAYCREDITS_BY_EMAIL' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT battlePayCredits FROM battlenet_accounts WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT battlePayCredits FROM battlenet_accounts WHERE email = ?',
        ],

        'AUTH_REMOVE_BATTLEPAYCREDITS_BY_EMAIL' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE battlenet_accounts SET battlePayCredits = battlePayCredits - ? WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE battlenet_accounts SET battlePayCredits = battlePayCredits - ? WHERE email = ?',
        ],

        'AUTH_GET_BANNED_ACTIVE_BY_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_CATA            => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_ONE                  => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_TWO                  => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_THREE                => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_FOUR                 => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_FIVE                 => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            CMANGOS_CLASSIC             => 'SELECT 1 FROM account_banned WHERE account_id = ? AND active = 1',
            CMANGOS_TBC                 => 'SELECT 1 FROM account_banned WHERE account_id = ? AND active = 1',
            CMANGOS_WOTLK               => 'SELECT 1 FROM account_banned WHERE account_id = ? AND active = 1',
            CMANGOS_CATA                => 'SELECT 1 FROM account_banned WHERE account_id = ? AND active = 1',
            VMANGOS_CLASSIC             => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            AZEROTHCORE_WOTLK           => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            SKYFIRE_MOP                 => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            ASHMANE_SHADOWLANDS         => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            ATLANTISS_CATA              => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            LEGIONCORE_735_SHA          => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_WOTLK_2016      => 'SELECT 1 FROM account_banned WHERE id = ? AND active = 1',
        ],

        'AUTH_GET_ACCOUNT_BAN_DURATION_STRING' => [
            TRINITYCORE_WOTLK           => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_CATA            => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_ONE                  => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_TWO                  => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_THREE                => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_FOUR                 => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            MANGOS_FIVE                 => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            CMANGOS_CLASSIC             => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            CMANGOS_TBC                 => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            CMANGOS_WOTLK               => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            CMANGOS_CATA                => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            VMANGOS_CLASSIC             => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            AZEROTHCORE_WOTLK           => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            SKYFIRE_MOP                 => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            ASHMANE_SHADOWLANDS         => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            ATLANTISS_CATA              => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            LEGIONCORE_735_SHA          => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
            TRINITYCORE_WOTLK_2016      => 'SELECT DATE_FORMAT(FROM_UNIXTIME(unbandate), "%e %b %Y at %H:%i") FROM account_banned WHERE id = ? AND active = 1',
        ],

        'AUTH_GET_EMAIL_USING_MD5_USERNAME' => [
            TRINITYCORE_WOTLK           => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_CATA            => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_ONE                  => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_TWO                  => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_THREE                => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_FOUR                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            MANGOS_FIVE                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_CLASSIC             => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_TBC                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_WOTLK               => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            CMANGOS_CATA                => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            VMANGOS_CLASSIC             => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            AZEROTHCORE_WOTLK           => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            SKYFIRE_MOP                 => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            ASHMANE_SHADOWLANDS         => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            ATLANTISS_CATA              => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            LEGIONCORE_735_SHA          => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
            TRINITYCORE_WOTLK_2016      => 'SELECT email FROM account WHERE ? = MD5(LOWER(username))',
        ],

        'AUTH_INSERT_SHA_BATTLENET_ACCOUNT' => [
            ASHMANE_SHADOWLANDS         => 'INSERT INTO battlenet_accounts (email, sha_pass_hash) VALUES (?, ?)',
            LEGIONCORE_735_SHA          => 'INSERT INTO battlenet_accounts (email, sha_pass_hash) VALUES (?, ?)',
        ],

        'AUTH_INSERT_S_V_BATTLENET_ACCOUNT' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'INSERT INTO battlenet_accounts (email, salt, verifier) VALUES (?, ?, ?)',
        ],

        'AUTH_LINK_BATTLENET_ACCOUNT' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE account AS a JOIN battlenet_accounts AS b ON a.email = b.email SET a.battlenet_account = b.id WHERE a.email = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE account AS a JOIN battlenet_accounts AS b ON a.email = b.email SET a.battlenet_account = b.id WHERE a.email = ?',
            LEGIONCORE_735_SHA          => 'UPDATE account AS a JOIN battlenet_accounts AS b ON a.email = b.email SET a.battlenet_account = b.id WHERE a.email = ?',
        ],

        'AUTH_GET_BATTLENET_ID_BY_EMAIL' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT id FROM battlenet_accounts WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT id FROM battlenet_accounts WHERE email = ?',
            LEGIONCORE_735_SHA          => 'SELECT id FROM battlenet_accounts WHERE email = ?',
        ],

        'AUTH_GET_BATTLENET_ID_BY_EMAIL_AND_SHA_PASS_HASH' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT id FROM battlenet_accounts WHERE email = ? AND sha_pass_hash = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT id FROM battlenet_accounts WHERE email = ? AND sha_pass_hash = ?',
            LEGIONCORE_735_SHA          => 'SELECT id FROM battlenet_accounts WHERE email = ? AND sha_pass_hash = ?',
        ],

        'AUTH_GET_BATTLENET_ID_BY_EMAIL' => [
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT id FROM battlenet_accounts WHERE email = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT id FROM battlenet_accounts WHERE email = ?',
            LEGIONCORE_735_SHA          => 'SELECT id FROM battlenet_accounts WHERE email = ?',
        ],

        'CHAR_GET_CHARACTERS_LIST_BY_ACCOUNT_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            TRINITYCORE_CATA            => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            MANGOS_ONE                  => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            MANGOS_TWO                  => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            MANGOS_THREE                => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            MANGOS_FOUR                 => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            MANGOS_FIVE                 => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            CMANGOS_CLASSIC             => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            CMANGOS_TBC                 => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            CMANGOS_WOTLK               => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            CMANGOS_CATA                => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            VMANGOS_CLASSIC             => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            AZEROTHCORE_WOTLK           => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            SKYFIRE_MOP                 => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            ATLANTISS_CATA              => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            LEGIONCORE_735_SHA          => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT `guid`, `name`, race, class, gender, `level` FROM characters WHERE account = ?',
        ],

        'CHAR_GET_CHARACTER_BY_ACCOUNT_ID_AND_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            TRINITYCORE_CATA            => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            MANGOS_ONE                  => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            MANGOS_TWO                  => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            MANGOS_THREE                => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            MANGOS_FOUR                 => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            MANGOS_FIVE                 => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            CMANGOS_CLASSIC             => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            CMANGOS_TBC                 => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            CMANGOS_WOTLK               => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            CMANGOS_CATA                => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            VMANGOS_CLASSIC             => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            AZEROTHCORE_WOTLK           => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            SKYFIRE_MOP                 => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            ATLANTISS_CATA              => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            LEGIONCORE_735_SHA          => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT 1 FROM characters WHERE account = ? AND `guid` = ?',
        ],

        'CHAR_IS_CHARACTER_GUID_BANNED' => [
            TRINITYCORE_WOTLK           => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            TRINITYCORE_CATA            => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            MANGOS_ONE                  => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            MANGOS_TWO                  => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            MANGOS_THREE                => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            MANGOS_FOUR                 => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            MANGOS_FIVE                 => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            CMANGOS_CLASSIC             => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            CMANGOS_TBC                 => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            CMANGOS_WOTLK               => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            CMANGOS_CATA                => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            VMANGOS_CLASSIC             => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            AZEROTHCORE_WOTLK           => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            SKYFIRE_MOP                 => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            ASHMANE_SHADOWLANDS         => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            ATLANTISS_CATA              => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            LEGIONCORE_735_SHA          => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
            TRINITYCORE_WOTLK_2016      => 'SELECT 1 FROM character_banned WHERE `guid` = ? AND active = 1',
        ],

        'CHAR_UPDATE_CHARACTER_ACCOUNT_ID' => [
            TRINITYCORE_WOTLK           => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            TRINITYCORE_CATA            => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            MANGOS_ONE                  => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            MANGOS_TWO                  => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            MANGOS_THREE                => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            MANGOS_FOUR                 => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            MANGOS_FIVE                 => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            CMANGOS_CLASSIC             => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            CMANGOS_TBC                 => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            CMANGOS_WOTLK               => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            CMANGOS_CATA                => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            VMANGOS_CLASSIC             => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            AZEROTHCORE_WOTLK           => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            SKYFIRE_MOP                 => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            ATLANTISS_CATA              => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            LEGIONCORE_735_SHA          => 'UPDATE characters SET account = ? WHERE `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'UPDATE characters SET account = ? WHERE `guid` = ?',
        ],

        'CHAR_GET_CHARACTER_NAME_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT `name` FROM characters WHERE `guid` = ?',
            TRINITYCORE_CATA            => 'SELECT `name` FROM characters WHERE `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT `name` FROM characters WHERE `guid` = ?',
            MANGOS_ONE                  => 'SELECT `name` FROM characters WHERE `guid` = ?',
            MANGOS_TWO                  => 'SELECT `name` FROM characters WHERE `guid` = ?',
            MANGOS_THREE                => 'SELECT `name` FROM characters WHERE `guid` = ?',
            MANGOS_FOUR                 => 'SELECT `name` FROM characters WHERE `guid` = ?',
            MANGOS_FIVE                 => 'SELECT `name` FROM characters WHERE `guid` = ?',
            CMANGOS_CLASSIC             => 'SELECT `name` FROM characters WHERE `guid` = ?',
            CMANGOS_TBC                 => 'SELECT `name` FROM characters WHERE `guid` = ?',
            CMANGOS_WOTLK               => 'SELECT `name` FROM characters WHERE `guid` = ?',
            CMANGOS_CATA                => 'SELECT `name` FROM characters WHERE `guid` = ?',
            VMANGOS_CLASSIC             => 'SELECT `name` FROM characters WHERE `guid` = ?',
            AZEROTHCORE_WOTLK           => 'SELECT `name` FROM characters WHERE `guid` = ?',
            SKYFIRE_MOP                 => 'SELECT `name` FROM characters WHERE `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT `name` FROM characters WHERE `guid` = ?',
            ATLANTISS_CATA              => 'SELECT `name` FROM characters WHERE `guid` = ?',
            LEGIONCORE_735_SHA          => 'SELECT `name` FROM characters WHERE `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT `name` FROM characters WHERE `guid` = ?',
        ],

        'CHAR_GET_CHARACTER_GUID_BY_NAME' => [
            TRINITYCORE_WOTLK           => 'SELECT `guid` FROM characters WHERE `name` = ?',
            TRINITYCORE_CATA            => 'SELECT `guid` FROM characters WHERE `name` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT `guid` FROM characters WHERE `name` = ?',
            MANGOS_ONE                  => 'SELECT `guid` FROM characters WHERE `name` = ?',
            MANGOS_TWO                  => 'SELECT `guid` FROM characters WHERE `name` = ?',
            MANGOS_THREE                => 'SELECT `guid` FROM characters WHERE `name` = ?',
            MANGOS_FOUR                 => 'SELECT `guid` FROM characters WHERE `name` = ?',
            MANGOS_FIVE                 => 'SELECT `guid` FROM characters WHERE `name` = ?',
            CMANGOS_CLASSIC             => 'SELECT `guid` FROM characters WHERE `name` = ?',
            CMANGOS_TBC                 => 'SELECT `guid` FROM characters WHERE `name` = ?',
            CMANGOS_WOTLK               => 'SELECT `guid` FROM characters WHERE `name` = ?',
            CMANGOS_CATA                => 'SELECT `guid` FROM characters WHERE `name` = ?',
            VMANGOS_CLASSIC             => 'SELECT `guid` FROM characters WHERE `name` = ?',
            AZEROTHCORE_WOTLK           => 'SELECT `guid` FROM characters WHERE `name` = ?',
            SKYFIRE_MOP                 => 'SELECT `guid` FROM characters WHERE `name` = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT `guid` FROM characters WHERE `name` = ?',
            ATLANTISS_CATA              => 'SELECT `guid` FROM characters WHERE `name` = ?',
            LEGIONCORE_735_SHA          => 'SELECT `guid` FROM characters WHERE `name` = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT `guid` FROM characters WHERE `name` = ?',
        ],

        'CHAR_GET_CHARACTER_INFO_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            TRINITYCORE_CATA            => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            MANGOS_ONE                  => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            MANGOS_TWO                  => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            MANGOS_THREE                => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            MANGOS_FOUR                 => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            MANGOS_FIVE                 => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            CMANGOS_CLASSIC             => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            CMANGOS_TBC                 => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            CMANGOS_WOTLK               => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            CMANGOS_CATA                => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            VMANGOS_CLASSIC             => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            AZEROTHCORE_WOTLK           => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            SKYFIRE_MOP                 => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            ATLANTISS_CATA              => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            LEGIONCORE_735_SHA          => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT `name`, race, class, gender, level, money, totalkills, online FROM characters WHERE `guid` = ?',
        ],

        'CHAR_GET_CHARACTER_PROFESSIONS_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            TRINITYCORE_CATA            => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            MANGOS_ONE                  => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            MANGOS_TWO                  => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            MANGOS_THREE                => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            MANGOS_FOUR                 => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            MANGOS_FIVE                 => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            CMANGOS_CLASSIC             => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            CMANGOS_TBC                 => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            CMANGOS_WOTLK               => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            CMANGOS_CATA                => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            VMANGOS_CLASSIC             => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            AZEROTHCORE_WOTLK           => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            SKYFIRE_MOP                 => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            ASHMANE_SHADOWLANDS         => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            ATLANTISS_CATA              => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            LEGIONCORE_735_SHA          => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
            TRINITYCORE_WOTLK_2016      => 'SELECT skill, value, max FROM character_skills WHERE `guid` = ? AND skill IN (129, 164, 165, 171, 182, 185, 186, 197, 202, 333, 356, 393, 755, 773)',
        ],

        'CHAR_GET_CHARACTER_RACE_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT race FROM characters WHERE `guid` = ?',
            TRINITYCORE_CATA            => 'SELECT race FROM characters WHERE `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT race FROM characters WHERE `guid` = ?',
            MANGOS_ONE                  => 'SELECT race FROM characters WHERE `guid` = ?',
            MANGOS_TWO                  => 'SELECT race FROM characters WHERE `guid` = ?',
            MANGOS_THREE                => 'SELECT race FROM characters WHERE `guid` = ?',
            MANGOS_FOUR                 => 'SELECT race FROM characters WHERE `guid` = ?',
            MANGOS_FIVE                 => 'SELECT race FROM characters WHERE `guid` = ?',
            CMANGOS_CLASSIC             => 'SELECT race FROM characters WHERE `guid` = ?',
            CMANGOS_TBC                 => 'SELECT race FROM characters WHERE `guid` = ?',
            CMANGOS_WOTLK               => 'SELECT race FROM characters WHERE `guid` = ?',
            CMANGOS_CATA                => 'SELECT race FROM characters WHERE `guid` = ?',
            VMANGOS_CLASSIC             => 'SELECT race FROM characters WHERE `guid` = ?',
            AZEROTHCORE_WOTLK           => 'SELECT race FROM characters WHERE `guid` = ?',
            SKYFIRE_MOP                 => 'SELECT race FROM characters WHERE `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'SELECT race FROM characters WHERE `guid` = ?',
            ATLANTISS_CATA              => 'SELECT race FROM characters WHERE `guid` = ?',
            LEGIONCORE_735_SHA          => 'SELECT race FROM characters WHERE `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT race FROM characters WHERE `guid` = ?',
        ],

        'CHAR_GET_CHARACTER_ONLINE_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            TRINITYCORE_CATA            => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            MANGOS_ONE                  => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            MANGOS_TWO                  => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            MANGOS_THREE                => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            MANGOS_FOUR                 => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            MANGOS_FIVE                 => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            CMANGOS_CLASSIC             => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            CMANGOS_TBC                 => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            CMANGOS_WOTLK               => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            CMANGOS_CATA                => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            VMANGOS_CLASSIC             => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            AZEROTHCORE_WOTLK           => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            SKYFIRE_MOP                 => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            ASHMANE_SHADOWLANDS         => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            ATLANTISS_CATA              => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            LEGIONCORE_735_SHA          => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
            TRINITYCORE_WOTLK_2016      => 'SELECT 1 FROM characters WHERE `guid` = ? AND `online` = 1',
        ],

        'CHAR_UPDATE_CHARACTER_LOCATION_BY_GUID' => [
            TRINITYCORE_WOTLK           => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            TRINITYCORE_CATA            => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            MANGOS_ONE                  => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            MANGOS_TWO                  => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            MANGOS_THREE                => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            MANGOS_FOUR                 => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            MANGOS_FIVE                 => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            CMANGOS_CLASSIC             => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            CMANGOS_TBC                 => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            CMANGOS_WOTLK               => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            CMANGOS_CATA                => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            VMANGOS_CLASSIC             => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            AZEROTHCORE_WOTLK           => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            SKYFIRE_MOP                 => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            ASHMANE_SHADOWLANDS         => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            ATLANTISS_CATA              => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            LEGIONCORE_735_SHA          => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
            TRINITYCORE_WOTLK_2016      => 'UPDATE characters SET map = ?, position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE `guid` = ?',
        ],

        'CHAR_GET_CHARACTERS_TICKETS_BY_ACCOUNT_ID' => [
            TRINITYCORE_WOTLK           => 'SELECT t.id, t.playerGuid, c.race, c.gender, t.`name`, t.`description`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_ticket t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
            TRINITYCORE_CATA            => 'SELECT t.id, t.playerGuid, c.race, c.gender, t.`name`, t.`description`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_ticket t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT t.id, t.playerGuid, c.race, c.gender, c.`name`, t.`note`, DATE_FORMAT(FROM_UNIXTIME(t.createtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.closedBy, t.closedBy FROM gm_bug t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
            MANGOS_ONE                  => 'SELECT t.ticket_id, t.guid, c.race, c.gender, c.`name`, t.`ticket_text`, DATE_FORMAT(FROM_UNIXTIME(t.ticket_lastchange), "%e %b %Y at %H:%i") as lastModifiedTime, t.resolved, t.resolved, t.resolved FROM character_ticket t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            MANGOS_TWO                  => 'SELECT t.ticket_id, t.guid, c.race, c.gender, c.`name`, t.`ticket_text`, DATE_FORMAT(FROM_UNIXTIME(t.ticket_lastchange), "%e %b %Y at %H:%i") as lastModifiedTime, t.resolved, t.resolved, t.resolved FROM character_ticket t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            MANGOS_THREE                => 'SELECT t.ticket_id, t.guid, c.race, c.gender, c.`name`, t.`ticket_text`, DATE_FORMAT(FROM_UNIXTIME(t.ticket_lastchange), "%e %b %Y at %H:%i") as lastModifiedTime, t.resolved, t.resolved, t.resolved FROM character_ticket t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            MANGOS_FOUR                 => 'SELECT t.ticket_id, t.guid, c.race, c.gender, c.`name`, t.`ticket_text`, DATE_FORMAT(FROM_UNIXTIME(t.ticket_lastchange), "%e %b %Y at %H:%i") as lastModifiedTime, t.resolved, t.resolved, t.resolved FROM character_ticket t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            MANGOS_FIVE                 => 'SELECT t.ticket_id, t.guid, c.race, c.gender, c.`name`, t.`ticket_text`, DATE_FORMAT(FROM_UNIXTIME(t.ticket_lastchange), "%e %b %Y at %H:%i") as lastModifiedTime, t.resolved, t.resolved, t.resolved FROM character_ticket t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            CMANGOS_CLASSIC             => 'SELECT t.id, t.author_guid, c.race, c.gender, t.`author_name`, t.`text`, DATE_FORMAT(FROM_UNIXTIME(t.updated), "%e %b %Y at %H:%i") as lastModifiedTime, t.closed, t.answered, t.seen FROM gm_tickets t JOIN characters c ON t.author_guid = c.guid WHERE t.author_guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            CMANGOS_TBC                 => 'SELECT t.id, t.author_guid, c.race, c.gender, t.`author_name`, t.`text`, DATE_FORMAT(FROM_UNIXTIME(t.updated), "%e %b %Y at %H:%i") as lastModifiedTime, t.closed, t.answered, t.seen FROM gm_tickets t JOIN characters c ON t.author_guid = c.guid WHERE t.author_guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            CMANGOS_WOTLK               => 'SELECT t.id, t.author_guid, c.race, c.gender, t.`author_name`, t.`text`, DATE_FORMAT(FROM_UNIXTIME(t.updated), "%e %b %Y at %H:%i") as lastModifiedTime, t.closed, t.answered, t.seen FROM gm_tickets t JOIN characters c ON t.author_guid = c.guid WHERE t.author_guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            CMANGOS_CATA                => 'SELECT t.id, t.author_guid, c.race, c.gender, t.`author_name`, t.`text`, DATE_FORMAT(FROM_UNIXTIME(t.updated), "%e %b %Y at %H:%i") as lastModifiedTime, t.closed, t.answered, t.seen FROM gm_tickets t JOIN characters c ON t.author_guid = c.guid WHERE t.author_guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            VMANGOS_CLASSIC             => 'SELECT t.ticket_id, t.guid, c.race, c.gender, t.`name`, t.`message`, DATE_FORMAT(FROM_UNIXTIME(t.last_modified_time), "%e %b %Y at %H:%i") as lastModifiedTime, t.closed_by, t.completed, t.viewed FROM gm_tickets t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            AZEROTHCORE_WOTLK           => 'SELECT t.id, t.playerGuid, c.race, c.gender, t.`name`, t.`description`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_ticket t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
            SKYFIRE_MOP                 => 'SELECT t.ticketid, t.guid, c.race, c.gender, t.name, t.message, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_tickets t JOIN characters c ON t.guid= c.guid WHERE t.guid IN (SELECT guid FROM characters WHERE account = ?)',
            ASHMANE_SHADOWLANDS         => 'SELECT t.id, t.playerGuid, c.race, c.gender, c.`name`, t.`note`, DATE_FORMAT(FROM_UNIXTIME(t.createTime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.closedBy, t.closedBy FROM gm_bug t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
            ATLANTISS_CATA              => 'SELECT t.ticketid, t.guid, c.race, c.gender, t.`name`, t.`message`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_tickets t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            LEGIONCORE_735_SHA          => 'SELECT t.ticketid, t.guid, c.race, c.gender, t.`name`, t.`message`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_tickets t JOIN characters c ON t.guid = c.guid WHERE t.guid IN (SELECT `guid` FROM characters WHERE account = ?)',
            TRINITYCORE_WOTLK_2016      => 'SELECT t.id, t.playerGuid, c.race, c.gender, t.`name`, t.`description`, DATE_FORMAT(FROM_UNIXTIME(t.lastmodifiedtime), "%e %b %Y at %H:%i") as lastModifiedTime, t.closedBy, t.completed, t.viewed FROM gm_ticket t JOIN characters c ON t.playerGuid = c.guid WHERE t.playerGuid IN (SELECT `guid` FROM characters WHERE account = ?)',
        ],

        'CHAR_GET_CHARACTERS_LADDERBOARD' => [
            TRINITYCORE_WOTLK           => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            TRINITYCORE_CATA            => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            MANGOS_ONE                  => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            MANGOS_TWO                  => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            MANGOS_THREE                => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            MANGOS_FOUR                 => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            MANGOS_FIVE                 => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            CMANGOS_CLASSIC             => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            CMANGOS_TBC                 => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            CMANGOS_WOTLK               => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            CMANGOS_CATA                => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            VMANGOS_CLASSIC             => 'SELECT "Unknown", 0, 0, 0, 0, 0, 0',
            AZEROTHCORE_WOTLK           => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            SKYFIRE_MOP                 => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            ASHMANE_SHADOWLANDS         => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            ATLANTISS_CATA              => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            LEGIONCORE_735_SHA          => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
            TRINITYCORE_WOTLK_2016      => 'SELECT name, race, gender, class, todaykills, yesterdaykills, totalkills FROM characters ORDER BY totalkills DESC LIMIT 100',
        ],

        'CHAR_GET_CHARACTERS_ONLINE' => [
            TRINITYCORE_WOTLK           => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            TRINITYCORE_CATA            => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            MANGOS_ONE                  => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            MANGOS_TWO                  => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            MANGOS_THREE                => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            MANGOS_FOUR                 => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            MANGOS_FIVE                 => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            CMANGOS_CLASSIC             => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            CMANGOS_TBC                 => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            CMANGOS_WOTLK               => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            CMANGOS_CATA                => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            VMANGOS_CLASSIC             => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            AZEROTHCORE_WOTLK           => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            SKYFIRE_MOP                 => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            ASHMANE_SHADOWLANDS         => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            ATLANTISS_CATA              => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            LEGIONCORE_735_SHA          => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
            TRINITYCORE_WOTLK_2016      => 'SELECT account, name, race, gender, class, level, zone FROM characters WHERE online = 1 LIMIT ?',
        ],

        'CHAR_GET_CHARACTERS_ONLINE_COUNT' => [
            TRINITYCORE_WOTLK           => 'SELECT count(*) FROM characters WHERE online = 1',
            TRINITYCORE_CATA            => 'SELECT count(*) FROM characters WHERE online = 1',
            TRINITYCORE_DRAGONFLIGHTS   => 'SELECT count(*) FROM characters WHERE online = 1',
            MANGOS_ONE                  => 'SELECT count(*) FROM characters WHERE online = 1',
            MANGOS_TWO                  => 'SELECT count(*) FROM characters WHERE online = 1',
            MANGOS_THREE                => 'SELECT count(*) FROM characters WHERE online = 1',
            MANGOS_FOUR                 => 'SELECT count(*) FROM characters WHERE online = 1',
            MANGOS_FIVE                 => 'SELECT count(*) FROM characters WHERE online = 1',
            CMANGOS_CLASSIC             => 'SELECT count(*) FROM characters WHERE online = 1',
            CMANGOS_TBC                 => 'SELECT count(*) FROM characters WHERE online = 1',
            CMANGOS_WOTLK               => 'SELECT count(*) FROM characters WHERE online = 1',
            CMANGOS_CATA                => 'SELECT count(*) FROM characters WHERE online = 1',
            VMANGOS_CLASSIC             => 'SELECT count(*) FROM characters WHERE online = 1',
            AZEROTHCORE_WOTLK           => 'SELECT count(*) FROM characters WHERE online = 1',
            SKYFIRE_MOP                 => 'SELECT count(*) FROM characters WHERE online = 1',
            ASHMANE_SHADOWLANDS         => 'SELECT count(*) FROM characters WHERE online = 1',
            ATLANTISS_CATA              => 'SELECT count(*) FROM characters WHERE online = 1',
            LEGIONCORE_735_SHA          => 'SELECT count(*) FROM characters WHERE online = 1',
            TRINITYCORE_WOTLK_2016      => 'SELECT count(*) FROM characters WHERE online = 1',
        ],
        
        'CMS_INSERT_ACCOUNT_DATA' => [
            CMS_FUSION_GEN              => 'INSERT INTO account_data (id, vp, dp, total_votes, nickname) VALUES (?, 0, 0, 0, ?)',
            CMS_BLIZZCMS                => 'INSERT INTO users (id, username, email, joindate, lastvisit, vp, dp) VALUES (?, ?, ?, UNIX_TIMESTAMP(), 0, 0, 0)',
            CMS_ACORE_CMS               => '', // not needed here
            CMS_WARCRY                  => 'INSERT INTO account_data (id, displayName, cooldowns, socialData, birthday, gender, secretAnswer, avatar, salt, selected_realm) 
                                                VALUES (?, ?, 0, 0, "unknown", "unknown", "unknown", "unknown", "unknown", 1)',
            CMS_FUSION_WOW_CMS          => 'INSERT INTO account_data (id, vp, dp, total_votes, nickname) VALUES (?, 0, 0, 0, ?)',
        ],

        'CMS_GET_VOTE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'SELECT vp FROM account_data WHERE id = ?',
            CMS_BLIZZCMS                => 'SELECT vp FROM users WHERE id = ?',
            CMS_WARCRY                  => 'SELECT silver FROM account_data WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'SELECT vp FROM account_data WHERE id = ?',
        ],

        'CMS_GET_VOTE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'SELECT meta_value FROM wp_usermeta WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_vp"',
        ],

        'CMS_GET_DONATE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'SELECT dp FROM account_data WHERE id = ?',
            CMS_BLIZZCMS                => 'SELECT dp FROM users WHERE id = ?',
            CMS_WARCRY                  => 'SELECT gold FROM account_data WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'SELECT dp FROM account_data WHERE id = ?',
        ],

        'CMS_GET_DONATE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'SELECT meta_value FROM wp_usermeta WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_dp"',
        ],

        'CMS_REMOVE_VOTE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'UPDATE account_data SET vp = vp - ? WHERE id = ?',
            CMS_BLIZZCMS                => 'UPDATE users SET vp = vp - ? WHERE id = ?',
            CMS_WARCRY                  => 'UPDATE account_data SET silver = silver - ? WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'UPDATE account_data SET vp = vp - ? WHERE id = ?',
        ],

        'CMS_REMOVE_VOTE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'UPDATE wp_usermeta SET meta_value = meta_value - ? WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_vp"',
        ],

        'CMS_REMOVE_DONATE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'UPDATE account_data SET dp = dp - ? WHERE id = ?',
            CMS_BLIZZCMS                => 'UPDATE users SET dp = dp - ? WHERE id = ?',
            CMS_WARCRY                  => 'UPDATE account_data SET gold = gold - ? WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'UPDATE account_data SET dp = dp - ? WHERE id = ?',
        ],

        'CMS_REMOVE_DONATE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'UPDATE wp_usermeta SET meta_value = meta_value - ? WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_dp"',
        ],

        'CMS_ADD_VOTE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'UPDATE account_data SET vp = vp + ? WHERE id = ?',
            CMS_BLIZZCMS                => 'UPDATE users SET vp = vp + ? WHERE id = ?',
            CMS_WARCRY                  => 'UPDATE account_data SET silver = silver + ? WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'UPDATE account_data SET vp = vp + ? WHERE id = ?',
        ],

        'CMS_ADD_VOTE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'UPDATE wp_usermeta SET meta_value = meta_value + ? WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_vp"',
        ],

        'CMS_ADD_DONATE_POINTS_BY_USER_ID' => [
            CMS_FUSION_GEN              => 'UPDATE account_data SET dp = dp + ? WHERE id = ?',
            CMS_BLIZZCMS                => 'UPDATE users SET dp = dp + ? WHERE id = ?',
            CMS_WARCRY                  => 'UPDATE account_data SET gold = gold + ? WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'UPDATE account_data SET dp = dp + ? WHERE id = ?',
        ],

        'CMS_ADD_DONATE_POINTS_BY_USERNAME' => [
            CMS_ACORE_CMS               => 'UPDATE wp_usermeta SET meta_value = meta_value + ? WHERE user_id = (SELECT id FROM wp_users WHERE user_nicename = ?) AND meta_key = "_dp"',
        ],

        'CMS_GET_VOTE_SITES' => [
            CMS_FUSION_GEN              => 'SELECT vs.id, vs.vote_sitename, vs.vote_url, vs.vote_image, vs.points_per_vote, hour_interval * 3600, COALESCE((SELECT time FROM vote_log vl WHERE vote_site_id = vs.id AND user_id = ? ORDER BY id DESC LIMIT 1), 0) AS last_time FROM vote_sites vs',
            CMS_BLIZZCMS                => 'SELECT vs.id, vs.name, vs.url, vs.image, vs.points, time * 3600, COALESCE((SELECT lasttime FROM votes_logs vl WHERE idvote = vs.id AND idaccount = ? ORDER BY id DESC LIMIT 1), 0) AS last_time FROM votes vs',
            CMS_ACORE_CMS               => 'SELECT vs.id, vs.vote_sitename, vs.vote_url, vs.vote_image, vs.points_per_vote, hour_interval * 3600, COALESCE((SELECT time FROM vote_log vl WHERE vote_site_id = vs.id AND user_id = ? ORDER BY id DESC LIMIT 1), 0) AS last_time FROM vote_sites vs',
            CMS_WARCRY                  => 'SELECT vs.id, vs.vote_sitename, vs.vote_url, vs.vote_image, vs.points_per_vote, hour_interval * 3600, COALESCE((SELECT timestamp FROM vote_data vd WHERE siteid = vs.id AND account = ? ORDER BY id DESC LIMIT 1), 0) AS last_time FROM vote_sites vs',
            CMS_FUSION_WOW_CMS          => 'SELECT vs.id, vs.vote_sitename, vs.vote_url, vs.vote_image, vs.points_per_vote, hour_interval * 3600, COALESCE((SELECT time FROM vote_log vl WHERE vote_site_id = vs.id AND user_id = ? ORDER BY id DESC LIMIT 1), 0) AS last_time FROM vote_sites vs',
        ],

        'CMS_GET_LAST_TIME_VOTED_UNIXTIMESTAMP' => [
            CMS_FUSION_GEN              => 'SELECT COALESCE((SELECT `time` FROM vote_log WHERE vote_site_id = ? AND user_id = ? ORDER BY `time` DESC LIMIT 1), 0) AS last_time',
            CMS_BLIZZCMS                => 'SELECT COALESCE((SELECT `lasttime` FROM votes_logs WHERE idvote = ? AND idaccount = ? ORDER BY `lasttime` DESC LIMIT 1), 0) AS last_time',
            CMS_ACORE_CMS               => 'SELECT COALESCE((SELECT `time` FROM vote_log WHERE vote_site_id = ? AND user_id = ? ORDER BY `time` DESC LIMIT 1), 0) AS last_time',
            CMS_WARCRY                  => 'SELECT COALESCE((SELECT `timestamp` FROM vote_data WHERE siteid = ? AND account = ? ORDER BY `timestamp` DESC LIMIT 1), 0) AS last_time;',
            CMS_FUSION_WOW_CMS          => 'SELECT COALESCE((SELECT `time` FROM vote_log WHERE vote_site_id = ? AND user_id = ? ORDER BY `time` DESC LIMIT 1), 0) AS last_time',
        ],

        'CMS_GET_VOTE_SITE_POINTS' => [
            CMS_FUSION_GEN              => 'SELECT points_per_vote FROM vote_sites WHERE id = ?',
            CMS_BLIZZCMS                => 'SELECT points FROM votes WHERE id = ?',
            CMS_ACORE_CMS               => 'SELECT points_per_vote FROM vote_sites WHERE id = ?',
            CMS_WARCRY                  => 'SELECT points_per_vote FROM vote_sites WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'SELECT points_per_vote FROM vote_sites WHERE id = ?',
        ],

        'CMS_GET_VOTE_SITE_COOLDOWN_IN_SECONDS' => [
            CMS_FUSION_GEN              => 'SELECT `hour_interval`*60*60 FROM vote_sites WHERE id = ?',
            CMS_BLIZZCMS                => 'SELECT `time`*60*60 FROM votes WHERE id = ?',
            CMS_ACORE_CMS               => 'SELECT `hour_interval`*60*60 FROM vote_sites WHERE id = ?',
            CMS_WARCRY                  => 'SELECT `hour_interval`*60*60 FROM vote_sites WHERE id = ?',
            CMS_FUSION_WOW_CMS          => 'SELECT `hour_interval`*60*60 FROM vote_sites WHERE id = ?',
        ],

        'CMS_INSERT_VOTE_LOG' => [
            CMS_FUSION_GEN              => 'INSERT INTO vote_log (vote_site_id, user_id, time) VALUES (?, ?, UNIX_TIMESTAMP())',
            CMS_BLIZZCMS                => 'INSERT INTO votes_logs (idvote, idaccount, lasttime, points, expired_at) VALUES (?, ?, UNIX_TIMESTAMP(), 1, UNIX_TIMESTAMP())',
            CMS_ACORE_CMS               => 'INSERT INTO vote_log (vote_site_id, user_id, time) VALUES (?, ?, UNIX_TIMESTAMP())',
            CMS_WARCRY                  => 'INSERT INTO vote_data (siteid, account, timestamp, ip) VALUES (?, ?, UNIX_TIMESTAMP(), "::0")',
            CMS_FUSION_WOW_CMS          => 'INSERT INTO vote_log (vote_site_id, user_id, time) VALUES (?, ?, UNIX_TIMESTAMP())',
        ],

        'CMS_GET_CHANGELOGS' => [
            CMS_FUSION_GEN              => 'SELECT change_id, (SELECT typeName FROM changelog_type WHERE id=type), changelog, time FROM changelog ORDER BY time DESC',
            CMS_BLIZZCMS                => 'SELECT id, title, description, date FROM changelogs ORDER BY date DESC',
            CMS_ACORE_CMS               => '', // unknown structure
            CMS_WARCRY                  => 'SELECT id, "Changelog", text, time FROM changelogs ORDER BY time DESC',
            CMS_FUSION_WOW_CMS          => 'SELECT change_id, (SELECT typeName FROM changelog_type WHERE id=type), changelog, time FROM changelog ORDER BY time DESC',
        ],

        'CMS_GET_ARTICLES' => [
            CMS_FUSION_GEN              => 'SELECT id, DATE_FORMAT(FROM_UNIXTIME(`timestamp`), "%e %M %Y"), (SELECT `nickname` FROM `account_data` WHERE id = author_id), 
                                            type_content, headline_en, content_en, headline_de, content_de, headline_es, content_es, headline_fr, content_fr, headline_no, 
                                            content_no, headline_ro, content_ro, headline_se, content_se, headline_ru, content_ru, headline_zh, content_zh, 
                                            headline_ko, content_ko FROM articles ORDER BY id DESC',
            CMS_BLIZZCMS                => 'SELECT id, DATE_FORMAT(`date`, "%e %M %Y"), title, description, image FROM news ORDER BY id DESC',
            CMS_ACORE_CMS               => 'SELECT id, DATE_FORMAT(`date`, "%e %M %Y"), title, content, picture_url, author_id FROM articles ORDER BY id DESC',
            CMS_WARCRY                  => 'SELECT id, DATE_FORMAT(`added`, "%e %M %Y"), authorstr, title, text, image FROM news ORDER BY id DESC',
            CMS_FUSION_WOW_CMS          => 'SELECT id, DATE_FORMAT(FROM_UNIXTIME(`timestamp`), "%e %M %Y"), (SELECT `nickname` FROM `account_data` WHERE id = author_id), 
                                            type_content, headline, content FROM articles ORDER BY id DESC',
        ],
    ];
}
